### ISSUE TITLE
[Tracking] Improve benchmark visibility / monitoring

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/coiled-runtime#148]
More details to come...

EDIT: 

### Infrastructure:

_Issues related to moving to moving to a proper benchmarking framework_ 

- [x] https://github.com/coiled/coiled-runtime/issues/186
- [x] https://github.com/coiled/coiled-runtime/issues/187
- [x] https://github.com/coiled/coiled-runtime/issues/188

### Monitoring:

_Issues related to increasing visibility of benchmark performance (should be addressed after infrastructure section above is complete)_

- [x] https://github.com/coiled/coiled-runtime/issues/189
- [x] https://github.com/coiled/coiled-runtime/issues/190
- [x] https://github.com/coiled/coiled-runtime/issues/192

**Comment by mrocklin** [comment]
I'd love to learn more about this.  In particular when thinking about Coiled Analtyics (which I'm thinking about now) I'm curious what we would need to build to satisfy this need.  I _don't_ think that folks should block on Coiled Analytics work here though (asv or whatever is probably better).  I'm just looking forward to learning more.

**Comment by fjetter** [comment]
A couple of requirements I see for our benchmarking suite

- Ability to record historical data
- Compare two commits or two different configurations (e.g. to verify feature toggles or test PRs)
- Be able to test PRs or commits on dask/dask and dask/distributed (this is likely rather a coiled-runtime feature overall)
- Measure and record runtime, peak memory usage, (probably something else as well)
- store various artifacts produced during the run (e.g. performance report or cluster memory timeline)

Some of this does not need to be part of the [tooling](https://github.com/coiled/coiled-runtime/issues/186) we're using and could be part of additional helper scripts or part of how the CI works.

**Comment by ncclementi** [comment]
Closing this as all the tracking points in the opening comment have been completed.
